import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                style={{
                    maxWidth: "430px",
                    width: "100%",
                    height: "100%",
                    margin: "auto",
                    marginTop: 0,
                    padding: 0,
                    boxSizing: "border-box",
                    overflowX: "hidden"
                }}
            >
                {children}
            </body>
        </html>
    );
}
